name: simple_web
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Rodrigo Muniz <rtmuniz@positivo.com.br>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  pwa:
    path: '../../../'

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
