/// URLs for offline cache.
final List<String> offlineUrls = [
  './',
  './.build.manifest',
  './.packages',
  './favicon.ico',
  './main.dart.js',
  './manifest.json',
  './packages/\$sdk/_internal/ddc_sdk.sum',
  './packages/\$sdk/_internal/strong.sum',
  './packages/\$sdk/dev_compiler/amd/dart_sdk.js',
  './packages/\$sdk/dev_compiler/amd/require.js',
  './packages/\$sdk/dev_compiler/common/dart_sdk.js',
  './packages/\$sdk/dev_compiler/common/run.js',
  './packages/\$sdk/dev_compiler/es6/dart_sdk.js',
  './packages/\$sdk/dev_compiler/kernel/amd/dart_sdk.js',
  './packages/\$sdk/dev_compiler/kernel/amd/require.js',
  './packages/\$sdk/dev_compiler/kernel/common/dart_sdk.js',
  './packages/\$sdk/dev_compiler/kernel/common/run.js',
  './packages/\$sdk/dev_compiler/kernel/es6/dart_sdk.js',
  './packages/\$sdk/dev_compiler/web/dart_stack_trace_mapper.js',
  './packages/\$sdk/dev_compiler/web/ddc_web_compiler.js',
  './packages/build_runner/src/server/build_updates_client/hot_reload_client.dart.js',
  './packages/build_runner/src/server/build_updates_client/live_reload_client.js',
  './packages/build_runner/src/server/graph_viz.html',
  './packages/build_runner/src/server/graph_viz.js',
  './packages/build_runner/src/server/graph_viz_main.dart.js',
  './packages/build_web_compilers/src/dev_compiler_stack_trace/stack_trace_mapper.dart.js',
  './packages/front_end/src/fasta/TESTING.md',
  './packages/front_end/src/fasta/diagnostics.md',
  './packages/front_end/src/fasta/parser/parser.md',
  './packages/kernel/binary/readme.md',
  './packages/kernel/target/readme.md',
  './packages/kernel/text/readme.md',
  './packages/pedantic/analysis_options.1.0.0.yaml',
  './packages/pedantic/analysis_options.1.1.0.yaml',
  './packages/pedantic/analysis_options.1.2.0.yaml',
  './packages/pedantic/analysis_options.1.3.0.yaml',
  './packages/pedantic/analysis_options.1.4.0.yaml',
  './packages/pedantic/analysis_options.1.5.0.yaml',
  './packages/pedantic/analysis_options.1.6.0.yaml',
  './packages/pedantic/analysis_options.1.7.0.yaml',
  './packages/pedantic/analysis_options.1.8.0.yaml',
  './packages/pedantic/analysis_options.yaml',
  './styles.css',
];

/// Last modified timestamp of the files
final String lastModified = '2019-07-13T04:08:41.126Z';
